### ISSUE TITLE
[bug] 투두 등록하려고 엔터입력 시

### ISSUE THREAD

**Issue by xdfc1745** [xoxwgys56/chakra-react-typescript-practice#1]
![image](https://user-images.githubusercontent.com/39234312/148016624-87b266a6-7d69-4765-b8f7-94d8d3e3b05b.png)

`우리` 라는 todo를 입력하고 엔터를 입력 시, 위의 사진과 입력한 글과 글의 마지막 글로 2개의 todo가 입력됩니다.

**Comment by xoxwgys56** [comment]
@xdfc1745 

이슈가 해결되었습니다. 제보해주셔서 감사합니다. 수정사항은 f561ca99b5119e7528760c021faf9c261b2f8eb6 에 반영되었습니다.    
*commit*에도 써있지만, 참고한 url을 공유합니다. https://www.inflearn.com/questions/9010
